env:
  node: true

parserOptions:
  ecmaVersion: 9

extends:
  - "eslint:recommended"
  - prettier

rules:
  # Override some recommended rules.
  no-unused-vars: ["error", {"args": "none"}]
  no-empty: ["error", { "allowEmptyCatch": true }]

  strict: ["error", "safe"]
  no-loop-func: "error"
  no-trailing-spaces: "error"
  eol-last: "error"
