env:
  node: true

parserOptions:
  ecmaVersion: 9
  # Override eslint-config-standard, which incorrectly sets this to "module",
  # though that setting is only for ES6 modules, not CommonJS modules.
  sourceType: 'script'

extends:
  - 'eslint:recommended'
  - standard
  - prettier
  - plugin:jsdoc/recommended

plugins:
  - mocha

settings:
  jsdoc:
    mode: 'typescript'
    tagNamePreference:
      returns: 'return'

overrides:
  - files:
      - 'tests/**/*.js'
    env:
      mocha: true
    rules:
      mocha/no-exclusive-tests: 'error'

rules:
  # TODO These are included in standard and should be cleaned up and turned on.
  node/no-deprecated-api: 'off' # we still make heavy use of url.parse

  # JSDoc modifications
  jsdoc/check-types: 'off'
  jsdoc/no-undefined-types: 'off'
  jsdoc/require-jsdoc: 'off'
  jsdoc/require-param-description: 'off'
  jsdoc/require-returns-description: 'off'
  jsdoc/valid-types: 'off'

  # Nock additions.
  strict: ['error', 'safe']
  no-loop-func: 'error'
  no-var: 'error'
  prefer-const: 'error'
  object-shorthand: ['error', 'properties']
  prefer-template: 'error'
  arrow-body-style: ['error', 'as-needed']
  prefer-destructuring:
    [
      'error',
      {
        'VariableDeclarator': { 'array': false, 'object': true },
        'AssignmentExpression': { 'array': false, 'object': false },
      },
    ]
