language: node_js
cache: npm

branches:
  only:
    - /^greenkeeper/prettier.*$/

# TODO: move over to separate action
jobs:
  include:
    - stage: update-prettier
      node_js: lts/*
      script:
        - git checkout $TRAVIS_BRANCH
        - npm run format:fix
        # commit changes and push back to branch on GitHub. If there are no changes then exit without error
        - 'git commit -a -m "style: prettier" && git push "https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG" ${TRAVIS_BRANCH} || true'
